import os
import sys

import psycopg2 as dbapi2


INIT_STATEMENTS = [
    "CREATE DOMAIN GENDERTYPE AS CHAR(1) CHECK ((VALUE == 'M') OR (VALUE == 'F') OR (VALUE == 'O'))",
    "CREATE TABLE PERSON (ID SERIAL PRIMARY KEY, NAME VARCHAR(40) NOT NULL, SURNAME VARCHAR(40) NOT NULL, GENDER GENDERTYPE NOT NULL, DATEOFBIRTH DATE NOT NULL, NATIONALITY VARCHAR(40))",
    "CREATE TABLE CUSTOMER (CUSTOMER_ID SERIAL PRIMARY KEY, PERSON_ID INTEGER REFERENCES PERSON (ID), USERNAME VARCHAR(20) UNIQUE NOT NULL, PHONE INTEGER UNIQUE NOT NULL, EMAIL VARCHAR(50) UNIQUE NOT NULL, ACTIVE BOOLEAN DEFAULT TRUE)",
    "CREATE TABLE ADDRESS (ADDRESS_ID SERIAL PRIMARY KEY, COUNTRY VARCHAR(40) NOT NULL, CITY VARCHAR(40) NOT NULL, DISTRICT VARCHAR(40) NOT NULL, NEIGHBORHOOD VARCHAR(40) NOT NULL, AVENUE VARCHAR(40) NOT NULL, STREET VARCHAR(40) NOT NULL, ADDR_NUM INTEGER NOT NULL, ZIPCODE INTEGER, DIRECTIONS VARCHAR(200), ADDRESS_NAME VARCHAR(30) NOT NULL)",
]


def initialize(url):
    with dbapi2.connect(url) as connection:
        cursor = connection.cursor()
        for statement in INIT_STATEMENTS:
            cursor.execute(statement)
        cursor.close()


if __name__ == "__main__":
    url = os.getenv("DATABASE_URL")
    if url is None:
        print("Usage: DATABASE_URL=url python dbinit.py", file=sys.stderr)
        sys.exit(1)
    initialize(url)